openapi: 3.0.0
info:
  version: 1.24.0-rev1
  title: Compliance MiniDashboard API
  description: >
    The MiniDashboard API is a modern REST API based on the OpenAPI
    specification. Date: January 4th. [Recent Updates](https://developer.cisco.com/)
  contact:
    name: Developer Community
    url: https://developer.cisco.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.mini.com/api/v1

security:
  - mini_api_key: []
components:
  securitySchemes:
    mini_api_key:
      type: apiKey
      name: X-Mini-Dashboard-API-Key
      in: header
      description: Secret to access the API
      
paths:
  /organizations:
    get:
      operationId: getOrganizations
      description: List the organizations that the user has privileges on
      summary: List Organizations
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Organization Identifier
                    name:
                      type: string
                      description: Organization Name
                    url:
                      type: string
                      description: Organization Url
                    api:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          description: Enable API access
                      description: API settings"
                    licensing:
                      type: object
                      properties:
                        model:
                          type: string
                          enum:
                            - co-term
                            - per-device
                            - subscription
                          description: "Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'."
                      description: Licensing settings
                    cloud:
                      type: object
                      properties:
                        region:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of theregion
                          description: Region details
                      description: Cloud infrastructure details
              examples:
                CiscoOffices:
                  value:
                    - id: SanFrancisco
                      name: San Francisco HeadQuarters
                      url: https://dashboard.mini.com/o/SanFrancisco/manage/organization/overview
                      api:
                        enabled: true
                      licensing:
                        model: subscription
                      cloud:
                        region:
                          name: North America
                    - id: Amsterdam
                      name: Amsterdam Office
                      url: https://dashboard.mini.com/o/Amsterdam/manage/organization/overview
                      api:
                        enabled: true
                      licensing:
                        model: co-term
                      cloud:
                        region:
                          name: "EMEAR"
        '401': 
          description: Unauthorized
        '429': 
          description: Too many requests
        '500':
          description: Internal service error
        '502':
          description: Bad gateway
        '503':
          description: Service unavailable
        '504':
          description: Gateway timeout
      tags:
        - read
    post:
      operationId: createOrganization
      description: Create a new organization
      summary: Create Organization
      requestBody:
        description: Details of the organization to create
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the organization
                licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing related settings
              required:
                - name
                - licensing
            examples:
              AmsterdamOffice:
                value:
                  name: Amsterdam Office
                  licensing:
                    model: subscription
        required: true
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization Identifier
                  name:
                    type: string
                    description: Organization Name
                  url:
                    type: string
                    description: Organization Url
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API related settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing related settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region info
                    description: Data for this organization
              examples:
                Amsterdam:
                  value:
                    id: Amsterdam
                    name: Amsterdam Office
                    url: https://dashboard.mini.com/o/Amsterdam/manage/organization/overview
                    api:
                      enabled: true
                    licensing:
                      model: co-term
                    cloud:
                      region:
                        name: EMEAR
        '400': 
          description: Bad request
        '401': 
          description: Unauthorized
        '403': 
          description: Forbidden
        '429': 
          description: Too many requests
        '500':
          description: Internal service error
        '502':
          description: Bad gateway
        '503':
          description: Service unavailable
        '504':
          description: Gateway timeout
      tags:
        - configure
  /organizations/{id}:
    get:
      operationId: getOrganization
      description: Fetch details for the specified organization
      summary: Get Organization Details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: Amsterdam
          description: Organization Identifier
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization Identifier
                  name:
                    type: string
                    description: Organization Name
                  url:
                    type: string
                    description: Organization Url
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region details
                    description: Cloud infrastructure details
              examples:
                SanFrancisco:
                  value:
                    id: SanFrancisco
                    name: San Francisco HeadQuarters 
                    url: https://dashboard.mini.com/o/SanFrancisco/manage/organization/overview
                    api:
                      enabled: true
                    licensing:
                      model: co-term
                    cloud:
                      region:
                        name: North America
        '401': 
          description: Unauthorized
        '403': 
          description: Forbidden
        '429': 
          description: Too many requests
        '500':
          description: Internal service error
        '502':
          description: Bad gateway
        '503':
          description: Service unavailable
        '504':
          description: Gateway timeout
      tags:
        - read
    put:
      operationId: updateOrganization
      description: Update the organization with the provided identifier
      summary: Update Organization
      parameters:
        - name: id
          in: path
          schema:
            type: string
            example: Amsterdam
          required: true
          description: Organization Identifier
      requestBody:
        description: organization to update
        content:
          application/json:
            schema:   
              type: object
              properties:
                name:
                  type: string
                  description: The name of the organization
                api:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      description: If true, enable the access to the Mini Dashboard API
                  description: API-specific settings
            examples:
              Amsterdam:
                value:
                  name: Amsterdam Office
                  api:
                    enabled: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization Identifier
                  name:
                    type: string
                    description: Organization Name
                  url:
                    type: string
                    description: Organization Url
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region details
                    description: Cloud nfrastructure details
              examples:
                SanFrancisco:
                  value:
                    id: SanFrancisco
                    name: San Francisco HeadQuarters
                    url: https://dashboard.mini.com/o/SanFrancisco/manage/organization/overview
                    api:
                      enabled: true
                    licensing:
                      model: co-term
                    cloud:
                      region:
                        name: North America
        '400': 
          description: Bad request
        '401': 
          description: Unauthorized
        '403': 
          description: Forbidden
        '429': 
          description: Too many requests
        '500':
          description: Internal service error
        '502':
          description: Bad gateway
        '503':
          description: Service unavailable
        '504':
          description: Gateway timeout
      tags:
        - configure
    delete:
      operationId: deleteOrganization
      description: Removes the organization with the provided identifier
      summary: Delete Organization
      parameters:
        - name: id
          in: path
          schema:
            type: string
            example: Amsterdam
          required: true
          description: Organization Identifier
      responses:
        '204':
          description: Success
        '401': 
          description: Unauthorized
        '403': 
          description: Forbidden
        '429': 
          description: Too many requests
        '500':
          description: Internal service error
        '502':
          description: Bad gateway
        '503':
          description: Service unavailable
        '504':
          description: Gateway timeout
      tags:
        - configure 
  
tags:
  - name: read
    description: "Read Operations"
  - name: configure
    description: "Read/Write Operations"
