openapi: 3.0.0
info:
  version: 1.26.0-Rev.1
  title: IncrementalSteps MiniDashboard API
  description: >
    The MiniDashboard API is a modern REST API based on the OpenAPI
    specification. 
    [Recent Updates](https://developer.cisco.com/)
  contact:
    name: Developer Community
    url: https://developer.cisco.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://incrementalsteps.io/api/v1

security:
  - mini_api_key: []
components:
  securitySchemes:
    mini_api_key:
      type: apiKey
      name: X-Incremental-Dashboard-API-Key
      in: header
      description: "API Key HTTP Header"
      
paths:
  /organizations:
    get:
      description: List the organizations that the user has privileges on
      operationId: getOrganizations
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Organization ID
                    name:
                      type: string
                      description: Organization name
                    url:
                      type: string
                      description: Organization URL
                    api:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          description: Enable API access
                      description: API related settings
                    licensing:
                      type: object
                      properties:
                        model:
                          type: string
                          enum:
                            - co-term
                            - per-device
                            - subscription
                          description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                      description: Licensing related settings
                    cloud:
                      type: object
                      properties:
                        region:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of region
                          description: Region info
                      description: Data for this organization
                    management:
                      type: object
                      properties:
                        details:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                description: Name of management data
                              value:
                                type: string
                                description: Value of management data
                          description: Details related to organization management, possibly empty
                      description: Information about the organization's management system
              example:
                - id: '2930418'
                  name: My organization
                  url: https://dashboard.mini.com/o/VjjsAd/manage/organization/overview
                  api:
                    enabled: true
                  licensing:
                    model: co-term
                  cloud:
                    region:
                      name: North America
                  management:
                    details:
                      - name: MSP ID
                        value: '123456'
        '401': 
          description: unauthorized
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: List the organizations that the user has privileges on
      tags:
        - read
    post:
      description: Create a new organization
      operationId: createOrganization
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the organization
                management:
                  type: object
                  properties:
                    details:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of management data
                          value:
                            type: string
                            description: Value of management data
                      description: Details related to organization management, possibly empty
                  description: Information about the organization's management system
              required:
                - name
            example:
              name: My organization
              management:
                details:
                  - name: MSP ID
                    value: '123456'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization ID
                  name:
                    type: string
                    description: Organization name
                  url:
                    type: string
                    description: Organization URL
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API related settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing related settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region info
                    description: Data for this organization
                  management:
                    type: object
                    properties:
                      details:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of management data
                            value:
                              type: string
                              description: Value of management data
                        description: Details related to organization management, possibly empty
                    description: Information about the organization's management system
              example:
                id: '2930418'
                name: My organization
                url: https://dashboard.mini.com/o/VjjsAd/manage/organization/overview
                api:
                  enabled: true
                licensing:
                  model: co-term
                cloud:
                  region:
                    name: North America
                management:
                  details:
                    - name: MSP ID
                      value: '123456'
        '400': 
          description: bad request
        '401': 
          description: unauthorized
        '403': 
          description: forbidden
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: Create a new organization
      tags:
        - configure
  /organizations/{organizationId}:
    get:
      description: Return an organization
      operationId: getOrganization
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization ID
                  name:
                    type: string
                    description: Organization name
                  url:
                    type: string
                    description: Organization URL
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API related settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing related settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region info
                    description: Data for this organization
                  management:
                    type: object
                    properties:
                      details:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of management data
                            value:
                              type: string
                              description: Value of management data
                        description: Details related to organization management, possibly empty
                    description: Information about the organization's management system
              example:
                id: '2930418'
                name: My organization
                url: https://dashboard.mini.com/o/VjjsAd/manage/organization/overview
                api:
                  enabled: true
                licensing:
                  model: co-term
                cloud:
                  region:
                    name: North America
                management:
                  details:
                    - name: MSP ID
                      value: '123456'
        '401': 
          description: unauthorized
        '403': 
          description: forbidden
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: Return an organization
      tags:
        - read
    put:
      description: Update an organization
      operationId: updateOrganization
      parameters:
        - name: organizationId
          in: path
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:   
              type: object
              properties:
                name:
                  type: string
                  description: The name of the organization
                management:
                  type: object
                  properties:
                    details:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of management data
                          value:
                            type: string
                            description: Value of management data
                      description: Details related to organization management, possibly empty
                  description: Information about the organization's management system
                api:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      description: If true, enable the access to the Incremental Dashboard API
                  description: API-specific settings
            example:
              name: My organization
              management:
                details:
                  - name: MSP ID
                    value: '123456'
              api:
                enabled: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization ID
                  name:
                    type: string
                    description: Organization name
                  url:
                    type: string
                    description: Organization URL
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API related settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing related settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region info
                    description: Data for this organization
                  management:
                    type: object
                    properties:
                      details:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of management data
                            value:
                              type: string
                              description: Value of management data
                        description: Details related to organization management, possibly empty
                    description: Information about the organization's management system
              example:
                id: '2930418'
                name: My organization
                url: https://dashboard.mini.com/o/VjjsAd/manage/organization/overview
                api:
                  enabled: true
                licensing:
                  model: co-term
                cloud:
                  region:
                    name: North America
                management:
                  details:
                    - name: MSP ID
                      value: '123456'
        '400': 
          description: bad request
        '401': 
          description: unauthorized
        '403': 
          description: forbidden
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: Update an organization
      tags:
        - configure
    delete:
      description: Delete an organization
      operationId: deleteOrganization
      parameters:
        - name: organizationId
          in: path
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Successful operation
        '401': 
          description: unauthorized
        '403': 
          description: forbidden
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: Delete an organization
      tags:
        - configure 
  
tags:
  - name: read
  - name: configure